# Generated by Django 5.1.6 on 2025-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('spaza', 'Spaza Shop'), ('freelancer', 'Freelancer'), ('delivery', 'Delivery Service'), ('other', 'Other')], max_length=20)),
                ('monthly_revenue', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank Deposits'), ('cash', 'Cash')], max_length=20)),
                ('business_age', models.IntegerField()),
                ('missed_payments', models.BooleanField(default=False)),
                ('credit_score', models.IntegerField(default=0)),
            ],
        ),
    ]
